/* This content is editable */
console.log("$(function () {$( '#selectable' ).selectable()});")
console.log("$(function () {$( '#selectable' ).selectable()});")
console.log("$(function () {$( '#selectable' ).selectable()});")
console.log("$(function () {$( '#selectable' ).selectable()});")
console.log('zfzef',345, "afgef")
console.log('zfzef',345, "afgef")
console.log('zfzef',345, "afgef")
console.log('zfzef',345, "afgef")
console.log('zfzef',345, "afgef")
console.log('zfzef',345, "afgef")
console.log('zfzef',345, "afgef")
console.log('zfzef',345, "afgef")
console.log('zfzef',345, "afgef")
console.log('zfzef',345, "afgef")
console.log('zfzef',345, "afgef")
console.log('zfzef',345, "afgef")
console.log('zfzef',345, "afgef")
